name: "user_web"
port: 8021
user_srv:
  host: "0.0.0.0"
  port: 50051
  name: "user_srv"

jwt:
  key: "f8s4sKt5G#oCi#qy1XczdKmeC#1Q%*nE"

sms:
  key: ""
  secret: ""
  expire: 300

redis:
  host: "127.0.0.1"
  port: 6379

consul:
  host: "192.168.1.102"
  port: 8500
