name: "goods_srv"
tags: ["xiaoke","srv","goods","goods_srv"]
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Root-123456"
  db: "xkshop_goods_srv"

consul:
  host: "192.168.1.101"
  port: 8500