version: 2.1

orbs:
  go: gotest/tools@0.0.13

workflows:
  ci:
    jobs:
    - go/test:
        name: test-golang-1.14
        executor:
          name: go/golang
          tag:  "1.14"
          cgo-enabled: "1"
        go-test-flags: -race
    - go/test:
        name: test-golang-1.15
        executor:
          name: go/golang
          tag:  "1.15"
          cgo-enabled: "1"
        go-test-flags: -race
    - go/test:
        name: test-golang-1.16
        executor:
          name: go/golang
          tag:  "1.16"
          cgo-enabled: "1"
        go-test-flags: -race
